# Generated by Django 5.2.4 on 2026-05-22 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffblog', '0005_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
